/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./BackOffice.module.css";

function BackOffice({ data }) {
  return (
    <div className={styles.backOffice}>
      <h2>Analyzed Contract Data</h2>
      <table className={styles.dataTable}>
        <thead>
          <tr>
            {Object.keys(data).map((key) => (
              <th key={key}>{key}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          <tr>
            {Object.values(data).map((value, index) => (
              <td key={index}>{value}</td>
            ))}
          </tr>
        </tbody>
      </table>
    </div>
  );
}

export default BackOffice;
