/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ContractAnalysisPortal.module.css";

function WelcomeSection({ getRootProps, getInputProps, isDragActive }) {
  return (
    <section
      {...getRootProps()}
      className={`${styles.welcomeSection} ${
        isDragActive ? styles.dragActive : ""
      }`}
    >
      <input {...getInputProps()} />
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/b41221eca74c3032aeb5ca36dac1abc47e07aaa423ce760c83c9c7240c9189f3?apiKey=91d213a11d04467fbe7727c237ada959&&apiKey=91d213a11d04467fbe7727c237ada959"
        className={styles.welcomeImage}
        alt="Welcome illustration"
      />
      <div className={styles.welcomeText}>
        <h1>Seja bem vindo(a), ao seu portal de análise de contratos</h1>
        <p>
          Arraste seus arquivos e pastas para cá ou use o botão "Enviar arquivo"
          para fazer upload e começar a analisar.
        </p>
      </div>
    </section>
  );
}

export default WelcomeSection;
